name: pnpm-lock.yaml
on:
  push:
    branches: [changeset-release/**]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Version Packages')
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 2
          persist-credentials: false
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.x.x
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Update lockfile
        run: pnpm install --ignore-scripts --lockfile-only
      - name: Config Git
        run: |
          BASIC_AUTH=$(echo -n "x-access-token:${{ secrets.BOT_GITHUB_TOKEN }}" | base64)
          echo "::add-mask::$BASIC_AUTH"
          git config --global user.name '${{ github.event.commits[0].author.name }}'
          git config --global user.email '${{ github.event.commits[0].author.email }}'
          git config --local http.$GITHUB_SERVER_URL/.extraheader "AUTHORIZATION: basic $BASIC_AUTH"
      - name: Commit changes
        run: |
          if [[ -n $(git status -s) ]]; then
            git add pnpm-lock.yaml
            git commit -m "Update pnpm-lock.yaml"
            git push
          else
            echo "No pnpm-lock.yaml changes necessary"
          fi
