# This workflow is necessary to work around Dependabot issues with Yarn 2.
# This should be removed after Dependabot fully supports Yarn 2.
#
# See: https://github.com/dependabot/dependabot-core/issues/1297

name: Dependabot
on:
  push:
    branches: [dependabot/npm_and_yarn/**]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          persist-credentials: false # minimize exposure
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12'
      - name: Autofix lockfile
        run: |
          # change directory
          # use $8 for default commit message style (Bump XXX from AAA to BBB in YYY)
          # use $9 for Angular commit style (build: bump XXX from AAA to BBB in YYY)
          cd .`git log -1 --pretty=%s | awk '{ print $8 }'`

          # restore yarn.lock from the previous commit
          git checkout HEAD^ -- yarn.lock

          # if package.json was not updated, upgrade the dependency
          # use $2 for default commit message style (Bump XXX from ...)
          # use $3 for Angular commit style (build: bump XXX from ...)
          git diff --name-only HEAD^ HEAD | grep -q 'package.json' || yarn up `git log -1 --pretty=%s | awk '{ print $2 }'`

          # restore package.json from the last commit
          git checkout HEAD -- package.json

          yarn install

          # deduplicate lockfile
          yarn dedupe
        env:
          YARN_ENABLE_SCRIPTS: 0 # disable postinstall scripts
      - name: Config Git
        run: |
          # use personal access token to allow triggering new workflow
          BASIC_AUTH=$(echo -n "x-access-token:${{ secrets.BOT_GITHUB_TOKEN }}" | base64)
          echo "::add-mask::$BASIC_AUTH"
          git config --global user.name '${{ github.event.commits[0].author.name }}'
          git config --global user.email '${{ github.event.commits[0].author.email }}'
          git config --local http.$GITHUB_SERVER_URL/.extraheader "AUTHORIZATION: basic $BASIC_AUTH"
      - name: Commit changes
        run: |
          cd .`git log -1 --pretty=%s | awk '{ print $8 }'` # ditto
          git add yarn.lock
          git commit -m "Dependabot Yarn 2 autofix"
          git push
